apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp-deployment
  labels:
    app: flaskapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
      - name: flaskapp
        image: sudhakshara/pythonflaskapp:latest
        ports:
        - containerPort: 8080
        env:
        - name: MYSQL_HOST
          value: "mysql-service"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "root"
        - name: MYSQL_DATABASE
          value: "MYUsers"

---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flaskapp
  ports:
    - protocol: TCP
      port: 80  # External port for the Flask app
      targetPort: 8080  # Flask container's internal port
      nodePort: 30090  # Specify the NodePort
  type: NodePort  # Ensure the service type is NodePort
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: sudhakshara/sqlapp:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_DATABASE
          value: "MYUsers"

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306  # Exposing MySQL service on port 3306
      targetPort: 3306
  type: ClusterIP  # Internal access to the d
